### ISSUE TITLE
[Bug] Wrong speedflip on kickoffs

### ISSUE THREAD

**Issue by NicEastvillage** [ItsCodeRed/RedUtils#6]
On kickoffs when the bot starts far back right, it will turn left towards the middle, then turn right again and perform a left speedflip. This is not the expected behvaiour, as speedflipping to the right should be easier. I do not know if the bug is in the Speedflip or the Kickoff.

**Comment by ItsCodeRed** [comment]
That's really strange, I do not experience this bug on my end, and I'm using the same version of the speedflip, and of the kickoff that's on github rn. For me, on a far back right kickoff, it turns ever so slightly right, then left, and then performs a right speedflip. Maybe you can send a gif of this behavior in action?

**Comment by NicEastvillage** [comment]
I looked at it again, and I noticed that you a speedflipping towards a point in front of the ball which is something I missed on first read. I also noticed that it happens on back left too. So now I am starting to think this behaviour is what you intend. Let's first confirm that. Here is an imgur album with RedUtils' speedflip on my pc using master as of right now: https://imgur.com/a/d1rWsO2. I also included a clip of Phoenix' speedflip kickoff to show what I imagined RedUtils' would do on kickoff on first read.

If this is what you intend the kickoff to look like, then my bad. However, I can highlight another problem then - it misses the small boost pad when starting on the left, so it has less boost after kickoff.

**Comment by ItsCodeRed** [comment]
Ok, so it turns out I misinterpreted your first message. I thought when you said "far back right kickoff", I thought you meant the diagonal back right. Whoops. Anyway now that I know what you're talking about, yeah that kickoff is incorrect. It was what I originally intended (obviously I didn't intend the boost miss), but regardless it is incorrect. I'll fix the kickoffs to look like an actual pros kickoffs in a bit.

**Comment by ItsCodeRed** [comment]
I believe this issue is fixed. Let me know if you have any more problems
